stages:
 - report

variables:
  SIGRID_CI_CUSTOMER: 'aqmdemo'
  SIGRID_CI_SYSTEM: 'hackme'
  SIGRID_CI_TARGET_QUALITY: '3.5'

sigridci:
  image: 
    name: 214775410005.dkr.ecr.eu-central-1.amazonaws.com/mendixpreprocessor:latest
  stage: report
  script: 
    - ""
  allow_failure: true
  artifacts:
    paths:
      - "sigrid-ci-output/*"
    expire_in: 1 week
    when: always
  tags:
    - run_docker
  except:
    variables:
      - $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

sigridcipublish:
  variables:
    SIGRID_CI_PUBLISH: 'publishonly'
  image: 
    name: 214775410005.dkr.ecr.eu-central-1.amazonaws.com/mendixpreprocessor:branch-container_only_uses_env_vars
  stage: report
  script: 
    - ""
  allow_failure: true
  tags:
    - run_docker
  only:
    variables:
      - $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

